s = '''ATGAGGCCATCATGTTATTTGGTATTCTTCTTGATATGCTTCATTTTGCCAAGTGATCACCAGAGCTGGG
GTTTAAGGACGATTCCTAAAGAGATAAAAATGAGTTGGCCGTGCCGAAAATGGCATCAAGGAGTTCACAA
CATAAAGGGACTAGAGTGTAAAAACACAGGTAAGGGCAAAGAAGGATGCCAGGACGATGGCGAGTCAGAA
GAGAGTATGTTTGAGAATGGAGACTATATCTACACCAACTCCCATCCATGA'''
s_new = s.replace('\n', '')
s_new = s_new.strip()
length = len(s_new)
print(length)
